# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Preapre Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js '20.x'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - run: npm --prefix server ci
      - run: npm --prefix client ci
      - run: npm install -g @vscode/vsce
      - run: vsce package
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: genericLSP
          path: |
            dist/server.js
      - name: VSCode Package
        uses: actions/upload-artifact@v4
        with:
          name: VSCode Package
          path: dts-lsp-*.vsix
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "0.0.3"
          tag_name: "0.0.3"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
